TOP=../..
include $(TOP)/configure/CONFIG
DB += IDM_defer.template
DB += IDM_gui.template
DB += IDM_encSync.template
DB += IDM_lim.template
DB += IDM_gap.template
DB += IDM_single.template
DB += IDM_posok.template
DB += IDM_stop.template


#USES_TEMPLATE += $(MOTOR)/db/motor.template
#USES_TEMPLATE += $(MOTOR)/db/basic_motor.template

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
